## data
train_file: /data/huangyuanhong/corpora/enwiki-dec2021/train/train-2000000.jsonl
dev_file: /data/huangyuanhong/corpora/enwiki-dec2021/test/test-10000.jsonl
max_seq_length: 336
retrieval_context_length: 180
preprocessing_num_workers: 32
overwrite_cache: false
max_train_samples: 1000

## model
model_name_or_path: '/data/huangyuanhong/huggingface/transformers/hub/models--mistralai--Mistral-7B-Instruct-v0.2/snapshots/3ad372fc79158a2148299e3318516c786aeded6c'
chat_format: mistral
retriever_name_or_path: /data/huangyuanhong/huggingface/transformers/Salesforce/SFR-Embedding-Mistral

## train
task_type: pretrain
workdir: .
learning_rate: 6.0e-3
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 1
use_flash_attn: true
alpha_nll: 1.0
clip_grad_norm: -1.0
seed: 980406
update_projector_only: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 4 ## assume there are 8 GPUs, so the total batch size is 384


## logging
logging_steps: 1
project_name: xrag_pretraining
exp_name: wikipedia_pretrain
checkpointing_steps: "epoch" ## string number or epoch


