## data
train_file: data/finetune/finetune_data_pwc_squad_shuffle-2.jsonl
max_seq_length: 1024
retrieval_context_single_max_len: 180
max_retrieval_context_length: 1024
preprocessing_num_workers: 8
overwrite_cache: false
use_rag_tuning: true
max_train_samples: 400000
output_dir: pretrained_model/qwen/
## model
model_name_or_path: pretrained_model/qwen/
chat_format: qwen
retriever_name_or_path: Salesforce/SFR-Embedding-Mistral
## train
task_type: finetune
workdir: .
learning_rate: 2.0e-5
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 1
alpha_nll: 1.0
alpha_kl: 2.0
kl_temperature: 1.0
clip_grad_norm: -1.0
seed: 980406
gradient_checkpointing: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
update_retriever_layers: 0
query_aware_rate: 0.1
use_split_pretrain: false
use_split_finetune: true
## logging
logging_steps: 1
project_name: prirag_finetune
checkpointing_steps: '200000'
